services:
  - rabbitmq
language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: gyFVw8LL7Mv8HAD+RCu693Y8/0yGGXSkhww6Fa2dGI/ZxRBvn7QhLgJ52T4D9H+Jo+TBqXzNBvrS0kkVoFWscarRAWzP+2wDY70x8J+NFVlU4FrfHATV3K2tkXSA3qscbSsikD2eSsOlT/s12Hm7ii3kgLd6uYtqIJVLl0MwwkJno+He6KRKp0MkeVjReIaCGsghvIERs3RPjsPf2zupMB7D100t56xPTlhYZr52cX9cUAjp7J6bHbvBXgRm2gwrx5tNHE1XDdED4QcT2zrKtfmM/E8bugfDeX5H9OmSq4kT6r3LvuP3f0RtUdatKocI90Wh/oZUpjTdFWTX82RlaTHb2sBr6N4+auLNHOVw4QKw7e53i8Yyais0mGmHNmbWQynYoclhwU+F4ggFOxCZ0FNpJ9cbkUn8zHBbAiOM8oyYkJVMfJwH9T6vDGPxkUM19IaRLlqFBO1aXeiL57i4AOFKInJk7tpt7yTQ/qvesSXznTML71ehwqD0W8+N7Bj0bPqtYd7mnXuvLcp9SF4gqWrDVbeXGw3SlUbhiMl9dLe45/ysE+Rgik64dujreFzvc4B1PIKhGdyfYBSdbe61xmmF0ovNSjycIZroEomDA18yivvo2fheiZSPJAoDEPqMtq2m7uDXAG/eFNocpt9RgP2Gggi8GSpEb1HJ61UHklI=
after_success:
- mvn clean test jacoco:report coveralls:report

